---
id: LoginTasks
name: LoginTasks
full: Login tasks library
description: A library for dealing with tasks run upon login to Horde applications.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_LoginTasks
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/translation: ^3
  optional:
    composer:
      horde/date: ^3
      horde/test: ^3
