---
id: LoginTasks
name: LoginTasks
full: Login tasks library
description: A library for dealing with tasks run upon login to Horde applications.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_LoginTasks
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.8
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Translation: ^2.2
  optional:
    pear:
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Test: ^2.1
